// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOSCmjQyfJ7ZzY6JmdyKr4B277go35ICw',
    appId: '1:277399625228:web:d56503f205604057911829',
    messagingSenderId: '277399625228',
    projectId: 'ascend-d2f5c',
    authDomain: 'ascend-d2f5c.firebaseapp.com',
    storageBucket: 'ascend-d2f5c.firebasestorage.app',
    measurementId: 'G-BQLM4FHH11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO6XCgkrveEBrV2K5wW0X3MLm7LTZZK-Q',
    appId: '1:277399625228:android:5ed360b75af98760911829',
    messagingSenderId: '277399625228',
    projectId: 'ascend-d2f5c',
    storageBucket: 'ascend-d2f5c.firebasestorage.app',
  );
}
